{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Failed systemd units",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_systemd_units{state=\"failed\"})"
    }
   ]
  },
  {
   "title": "Kernel Versions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (node_uname_info) by (release)",
     "legendFormat": "{{ release }}"
    }
   ]
  },
  {
   "title": "NGINX Requests served",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])",
     "legendFormat": "Requests {{ instance }}"
    },
    {
     "expr": "rate(nginx_connections_handled[5m])",
     "legendFormat": "Connections {{ instance }}"
    }
   ]
  }
 ]
}