{
 "title": "IPv6.watch",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "IPv6 Support",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ipv6_watch_summary == 1) / count(ipv6_watch_summary)"
    }
   ]
  },
  {
   "title": "IPv6 Support",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "count(ipv6_watch_summary == 1) / count(ipv6_watch_summary)",
     "legendFormat": "Full Support"
    },
    {
     "expr": "count(ipv6_watch_summary >= 0.5) / count(ipv6_watch_summary)",
     "legendFormat": "Partial Support"
    }
   ]
  },
  {
   "title": "AAAA status across sites",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg(ipv6_watch_has_ipv6) by (site)",
     "legendFormat": "{{ site }}"
    }
   ]
  },
  {
   "title": "Average result by DNS provider",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "avg(ipv6_watch_has_ipv6) by (resolver_provider)",
     "legendFormat": "{{ resolver_provider }}"
    }
   ]
  },
  {
   "title": "Average result by DNS server",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg(ipv6_watch_has_ipv6) by (resolver)",
     "legendFormat": "{{ resolver }}"
    }
   ]
  }
 ]
}