{
 "title": "Bridges",
 "tags": [ "matrix" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "bridge",
    "query": "label_values(bridge_matrix_request_seconds_count, bridge)"
   },
   { "name": "bucket_size", "query": "1m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_system_seconds_total{bridge=\"$bridge\"}[$bucket_size])",
     "legendFormat": "system"
    },
    {
     "expr": "rate(process_cpu_user_seconds_total{bridge=\"$bridge\"}[$bucket_size])",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(process_resident_memory_bytes{bridge=\"$bridge\"}[$bucket_size])",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(avg_over_time(nodejs_heap_size_total_bytes{bridge=\"$bridge\"}[$bucket_size]))",
     "legendFormat": "heap total"
    },
    {
     "expr": "sum(avg_over_time(nodejs_heap_size_used_bytes{bridge=\"$bridge\"}[$bucket_size]))",
     "legendFormat": "heap used"
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(process_open_fds{bridge=\"$bridge\"}[$bucket_size])",
       "legendFormat": "fds"
      }
     ]
    },
    {
     "title": "Event loop lag",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(nodejs_eventloop_lag_seconds{bridge=\"$bridge\"}[$bucket_size])",
       "legendFormat": "seconds"
      }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Remote User Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "bridge_remote_ghosts{bridge=\"$bridge\"}",
       "legendFormat": "remote"
      }
     ]
    },
    {
     "title": "Matrix Intents",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "bridge_matrix_ghosts{bridge=\"$bridge\"}",
       "legendFormat": "matrix"
      }
     ]
    },
    {
     "title": "Users by Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bridge_matrix_users_by_age{bridge=\"$bridge\"}",
       "legendFormat": "matrix {{age}}"
      },
      {
       "expr": "bridge_remote_users_by_age{bridge=\"$bridge\"}",
       "legendFormat": "remote {{age}}"
      }
     ]
    },
    {
     "title": "Active Users",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bridge_active_users{bridge=\"$bridge\", remote=\"true\"} > 0)",
       "legendFormat": "Remote"
      },
      {
       "expr": "sum(bridge_active_users{bridge=\"$bridge\", remote=\"false\"} > 0)",
       "legendFormat": "Matrix"
      }
     ]
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Known Rooms",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bridge_matrix_configured_rooms{bridge=\"$bridge\"}",
       "legendFormat": "matrix"
      },
      {
       "expr": "bridge_remote_configured_rooms{bridge=\"$bridge\"}",
       "legendFormat": "remote"
      }
     ]
    },
    {
     "title": "Rooms by Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bridge_matrix_rooms_by_age{bridge=\"$bridge\",age=\"1h\"}",
       "legendFormat": "matrix 1h"
      },
      {
       "expr": "bridge_remote_rooms_by_age{bridge=\"$bridge\",age=\"1h\"}",
       "legendFormat": "remote 1h"
      },
      {
       "expr": "bridge_matrix_rooms_by_age{bridge=\"$bridge\",age=\"1d\"}",
       "legendFormat": "matrix 1d"
      },
      {
       "expr": "bridge_remote_rooms_by_age{bridge=\"$bridge\",age=\"1d\"}",
       "legendFormat": "remote 1d"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "From Remote request rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(bridge_remote_request_seconds_count{bridge=\"$bridge\",outcome=\"success\"}[$bucket_size])",
       "legendFormat": "{{outcome}}"
      },
      {
       "expr": "rate(bridge_remote_request_seconds_count{bridge=\"$bridge\",outcome!=\"success\"}[$bucket_size])",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "title": "From Remote average request duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(bridge_remote_request_seconds_sum{bridge=\"$bridge\",outcome=\"success\"}[$bucket_size]) / rate(bridge_remote_request_seconds_count{bridge=\"$bridge\"}[$bucket_size])",
       "legendFormat": "{{outcome}}"
      },
      {
       "expr": "rate(bridge_remote_request_seconds_sum{bridge=\"$bridge\",outcome!=\"success\"}[$bucket_size]) / rate(bridge_remote_request_seconds_count{bridge=\"$bridge\"}[$bucket_size])",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "title": "From Matrix request rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(bridge_matrix_request_seconds_count{bridge=\"$bridge\",outcome=\"success\"}[$bucket_size])",
       "legendFormat": "{{outcome}}"
      },
      {
       "expr": "rate(bridge_matrix_request_seconds_count{bridge=\"$bridge\",outcome!=\"success\"}[$bucket_size])",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "title": "From Matrix average request duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(bridge_matrix_request_seconds_sum{bridge=\"$bridge\",outcome=\"success\"}[$bucket_size]) / rate(bridge_matrix_request_seconds_count{bridge=\"$bridge\"}[$bucket_size])",
       "legendFormat": "{{outcome}}"
      },
      {
       "expr": "rate(bridge_matrix_request_seconds_sum{bridge=\"$bridge\",outcome!=\"success\"}[$bucket_size]) / rate(bridge_matrix_request_seconds_count{bridge=\"$bridge\"}[$bucket_size])",
       "legendFormat": "{{outcome}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Matrix API Calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(bridge_matrix_api_calls{bridge=\"$bridge\"}[$bucket_size])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Remote API Calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(bridge_remote_api_calls{bridge=\"$bridge\"}[$bucket_size])",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IRC Specific",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "IRC Handler calls",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(bridge_irchandler_calls{bridge=\"$bridge\"}[$bucket_size])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Membersync Joins/Leaves",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 7, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bridge_user_join_queue{bridge=\"$bridge\"}",
       "legendFormat": "Matrix Users joining IRC"
      },
      {
       "expr": "bridge_user_leave_queue{bridge=\"$bridge\"}",
       "legendFormat": "IRC users leaving rooms"
      }
     ]
    },
    {
     "title": "Client Reconnects",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bridge_clientpool_reconnect_queue{bridge=\"$bridge\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Last successful scrape of master thread",
     "type": "graph",
     "description": "The metrics worker thread regularly reads from the master thread to gather metrics. If the master thread is not responding, this value will go up. This should normally never exceed 15s",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "metrics_worker_interval{bridge=\"$bridge\"}",
       "legendFormat": "Scrape time"
      }
     ]
    },
    {
     "title": "IRC Client connection states",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 7, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bridge_clientpool_client_states{bridge=\"$bridge\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    }
   ]
  }
 ]
}