{
  imports = [
    ../../modules/base.nix
    ../../modules/no-slipstream.nix
    ../../modules/authorative-dns.nix
    ../../modules/backup.nix
    ../../modules/blackbox_exporter.nix
    ../../modules/c3schedule.nix
    ../../modules/gitlab-runner2.nix
    ../../modules/knot_exporter.nix
    ../../modules/monitoring.nix
    ../../modules/prosody
    ../../modules/ssh-unlock.nix
    ../../modules/syncserver
    ../../modules/wireguard
    ../../modules/bird
    ../../modules/dn42
    ../../modules/photoprism.nix
    ../../modules/fping-exporter.nix
    ../../modules/publictransport.nix
    ../../modules/dendrite.nix
    ../../modules/dex.nix
    ../../modules/matrix-static.nix
  ];
}
